=== SenorPez/flight-manager/scheduler/destination.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Destinations",
  "description": "An array of destinations from a hub",
  "type": "object",
  "properties": {
    "hub": "string",
    "description": "ICAO airport code of destination",
    "latitude": {
      "type": "number",
      "description": "Latitude of the hub",
      "minimum": -90.0,
      "maximum": 90.0
    },
    "longitude": {
      "type": "number",
      "description": "Longitude of the hub",
      "minimum": -180.0,
      "maximum": 180.0
    },
    "destinations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "destination": {
            "type": "string",
            "description": "ICAO airport code of destination"
          },
          "routes": {
            "type": "integer",
            "description": "The number of routes from the hub to the destination",
            "minimum": 1
          },
          "latitude": {
            "type": "number",
            "description": "Latitude of the destination",
            "minimum": -90.0,
            "maximum": 90.0
          },
          "longitude": {
            "type": "number",
            "description": "Longitude of the destination",
            "minimum": -180.0,
            "maximum": 180.0
          }
        },
        "required": [
          "destination",
          "routes",
          "latitude",
          "longitude"
        ]
      }
    }
  }
}

=== SenorPez/flight-manager/scheduler/rksi.json
{
  "hub": "RKSI",
  "latitude": 37.4624977111816,
  "longitude": 126.439147949219,
  "destinations": [
    {
      "destination": "PANC",
      "routes": 15,
      "latitude": 61.1740875244141,
      "longitude": -149.998138427734
    },
    {
      "destination": "VVNB",
      "routes": 9,
      "latitude": 21.2216644287109,
      "longitude": 105.805541992188
    },
    {
      "destination": "KLAX",
      "routes": 8,
      "latitude": 33.9424743652344,
      "longitude": -118.409332275391
    },
    {
      "destination": "RJAA",
      "routes": 8,
      "latitude": 35.7652778625488,
      "longitude": 140.385559082031
    },
    {
      "destination": "ZSPD",
      "routes": 8,
      "latitude": 31.1450004577637,
      "longitude": 121.793334960938
    },
    {
      "destination": "VHHH",
      "routes": 7,
      "latitude": 22.3088836669922,
      "longitude": 113.914733886719
    },
    {
      "destination": "RPLL",
      "routes": 6,
      "latitude": 14.5100021362305,
      "longitude": 121.013610839844
    },
    {
      "destination": "RKPK",
      "routes": 6,
      "latitude": 35.1805572509766,
      "longitude": 128.938049316406
    },
    {
      "destination": "LOWW",
      "routes": 5,
      "latitude": 48.110279083252,
      "longitude": 16.5697326660156
    },
    {
      "destination": "WSSS",
      "routes": 5,
      "latitude": 1.35920715332031,
      "longitude": 103.989318847656
    },
    {
      "destination": "VTBS",
      "routes": 5,
      "latitude": 13.6858291625977,
      "longitude": 100.748901367188
    },
    {
      "destination": "ZGGG",
      "routes": 5,
      "latitude": 23.3933334350586,
      "longitude": 113.308319091797
    },
    {
      "destination": "RJBB",
      "routes": 5,
      "latitude": 34.4341659545898,
      "longitude": 135.232788085938
    },
    {
      "destination": "CYYZ",
      "routes": 3,
      "latitude": 43.6760711669922,
      "longitude": -79.6304702758789
    },
    {
      "destination": "EHAM",
      "routes": 3,
      "latitude": 52.3080558776856,
      "longitude": 4.76416015625
    },
    {
      "destination": "EDDF",
      "routes": 3,
      "latitude": 50.0333061218262,
      "longitude": 8.57044982910156
    },
    {
      "destination": "WIII",
      "routes": 3,
      "latitude": -6.12361145019531,
      "longitude": 106.661102294922
    },
    {
      "destination": "WMKK",
      "routes": 3,
      "latitude": 2.74333190917969,
      "longitude": 101.698059082031
    },
    {
      "destination": "WMKP",
      "routes": 3,
      "latitude": 5.29555511474609,
      "longitude": 100.272216796875
    },
    {
      "destination": "VVTS",
      "routes": 3,
      "latitude": 10.820556640625,
      "longitude": 106.660827636719
    },
    {
      "destination": "ZBAA",
      "routes": 3,
      "latitude": 40.0786972045898,
      "longitude": 116.594757080078
    },
    {
      "destination": "ZBTJ",
      "routes": 3,
      "latitude": 39.1233329772949,
      "longitude": 117.345001220703
    },
    {
      "destination": "RJFF",
      "routes": 3,
      "latitude": 33.5844421386719,
      "longitude": 130.45166015625
    },
    {
      "destination": "KJFK",
      "routes": 2,
      "latitude": 40.6413688659668,
      "longitude": -73.7776718139648
    },
    {
      "destination": "LIRF",
      "routes": 2,
      "latitude": 41.8002815246582,
      "longitude": 12.2388916015625
    },
    {
      "destination": "EGLL",
      "routes": 2,
      "latitude": 51.4775009155273,
      "longitude": -0.461380004882813
    },
    {
      "destination": "CYVR",
      "routes": 2,
      "latitude": 49.194694519043,
      "longitude": -123.183967590332
    },
    {
      "destination": "WADD",
      "routes": 2,
      "latitude": -8.74749755859375,
      "longitude": 115.169158935547
    },
    {
      "destination": "VVDN",
      "routes": 2,
      "latitude": 16.0438919067383,
      "longitude": 108.200286865234
    },
    {
      "destination": "ZLXY",
      "routes": 2,
      "latitude": 34.4449996948242,
      "longitude": 108.75
    },
    {
      "destination": "RCTP",
      "routes": 2,
      "latitude": 25.0802764892578,
      "longitude": 121.232208251953
    },
    {
      "destination": "RJCC",
      "routes": 2,
      "latitude": 42.7752799987793,
      "longitude": 141.692504882813
    },
    {
      "destination": "ZHCC",
      "routes": 2,
      "latitude": 34.5183334350586,
      "longitude": 113.839996337891
    },
    {
      "destination": "RJGG",
      "routes": 2,
      "latitude": 34.8583297729492,
      "longitude": 136.805267333984
    },
    {
      "destination": "RJNT",
      "routes": 2,
      "latitude": 36.6483306884766,
      "longitude": 137.1875
    },
    {
      "destination": "RJBE",
      "routes": 2,
      "latitude": 34.6327781677246,
      "longitude": 135.223876953125
    },
    {
      "destination": "ZYTX",
      "routes": 2,
      "latitude": 41.6416664123535,
      "longitude": 123.485015869141
    },
    {
      "destination": "KATL",
      "routes": 1,
      "latitude": 33.6408462524414,
      "longitude": -84.4271240234375
    },
    {
      "destination": "KIAD",
      "routes": 1,
      "latitude": 38.9474449157715,
      "longitude": -77.4599456787109
    },
    {
      "destination": "KDFW",
      "routes": 1,
      "latitude": 32.8968276977539,
      "longitude": -97.0379943847656
    },
    {
      "destination": "KBOS",
      "routes": 1,
      "latitude": 42.3629417419434,
      "longitude": -71.0063934326172
    },
    {
      "destination": "KORD",
      "routes": 1,
      "latitude": 41.9769401550293,
      "longitude": -87.9081497192383
    },
    {
      "destination": "LPPT",
      "routes": 1,
      "latitude": 38.774169921875,
      "longitude": -9.13417053222656
    },
    {
      "destination": "LEMD",
      "routes": 1,
      "latitude": 40.4722213745117,
      "longitude": -3.56082153320312
    },
    {
      "destination": "KLAS",
      "routes": 1,
      "latitude": 36.0800476074219,
      "longitude": -115.152236938477
    },
    {
      "destination": "NZAA",
      "routes": 1,
      "latitude": -37.008056640625,
      "longitude": 174.791687011719
    },
    {
      "destination": "KSFO",
      "routes": 1,
      "latitude": 37.6188087463379,
      "longitude": -122.375419616699
    },
    {
      "destination": "LFPG",
      "routes": 1,
      "latitude": 49.0097808837891,
      "longitude": 2.54774475097656
    },
    {
      "destination": "LIMC",
      "routes": 1,
      "latitude": 45.6300010681152,
      "longitude": 8.72305297851563
    },
    {
      "destination": "LSZH",
      "routes": 1,
      "latitude": 47.4583930969238,
      "longitude": 8.54789733886719
    },
    {
      "destination": "KSEA",
      "routes": 1,
      "latitude": 47.4489974975586,
      "longitude": -122.309310913086
    },
    {
      "destination": "YSSY",
      "routes": 1,
      "latitude": -33.9461898803711,
      "longitude": 151.173583984375
    },
    {
      "destination": "LKPR",
      "routes": 1,
      "latitude": 50.100830078125,
      "longitude": 14.2599945068359
    },
    {
      "destination": "LHBP",
      "routes": 1,
      "latitude": 47.4394454956055,
      "longitude": 19.2619476318359
    },
    {
      "destination": "YBBN",
      "routes": 1,
      "latitude": -27.384162902832,
      "longitude": 153.117523193359
    },
    {
      "destination": "PHNL",
      "routes": 1,
      "latitude": 21.3178176879883,
      "longitude": -157.920227050781
    },
    {
      "destination": "OMDB",
      "routes": 1,
      "latitude": 25.2527770996094,
      "longitude": 55.3644409179688
    },
    {
      "destination": "VIDP",
      "routes": 1,
      "latitude": 28.5686111450195,
      "longitude": 77.1122436523438
    },
    {
      "destination": "VTSP",
      "routes": 1,
      "latitude": 8.11250305175781,
      "longitude": 98.3091430664063
    },
    {
      "destination": "VNKT",
      "routes": 1,
      "latitude": 27.6961097717285,
      "longitude": 85.3605651855469
    },
    {
      "destination": "VVPQ",
      "routes": 1,
      "latitude": 10.1697235107422,
      "longitude": 103.993072509766
    },
    {
      "destination": "VYYY",
      "routes": 1,
      "latitude": 16.9072647094727,
      "longitude": 96.1332397460938
    },
    {
      "destination": "VDPP",
      "routes": 1,
      "latitude": 11.5466690063477,
      "longitude": 104.844146728516
    },
    {
      "destination": "VTCC",
      "routes": 1,
      "latitude": 18.7713851928711,
      "longitude": 98.9627685546875
    },
    {
      "destination": "VVCR",
      "routes": 1,
      "latitude": 11.9955596923828,
      "longitude": 109.218322753906
    },
    {
      "destination": "PGUM",
      "routes": 1,
      "latitude": 13.4839477539063,
      "longitude": 144.797119140625
    },
    {
      "destination": "RPVM",
      "routes": 1,
      "latitude": 10.3075637817383,
      "longitude": 123.979431152344
    },
    {
      "destination": "ZPPP",
      "routes": 1,
      "latitude": 25.1049957275391,
      "longitude": 102.941650390625
    },
    {
      "destination": "VMMC",
      "routes": 1,
      "latitude": 22.1494445800781,
      "longitude": 113.591400146484
    },
    {
      "destination": "ZGSZ",
      "routes": 1,
      "latitude": 22.6383285522461,
      "longitude": 113.811676025391
    },
    {
      "destination": "ZMUB",
      "routes": 1,
      "latitude": 47.8424987792969,
      "longitude": 106.767517089844
    },
    {
      "destination": "ZSAM",
      "routes": 1,
      "latitude": 24.5449981689453,
      "longitude": 118.126647949219
    },
    {
      "destination": "ZGHA",
      "routes": 1,
      "latitude": 28.1900024414062,
      "longitude": 113.218353271484
    },
    {
      "destination": "RCMQ",
      "routes": 1,
      "latitude": 24.2649993896484,
      "longitude": 120.620849609375
    },
    {
      "destination": "ZSFZ",
      "routes": 1,
